name: Deploy to qa
on:
  push:
    branches:
      - githubActions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add pem file and openVpn ovpn file
        run: |
          echo "${{secrets.BAHMNI_LITE_AWS_UAT_SSH_PRIVATE_KEY}}" > ~/private_key.pem && chmod 400 ~/private_key.pem

      - name: Set Up OpenVPN
        env:
          OPENVPN_CONFIG: ${{ secrets.UAT_OVPN_FILE }}
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn
          echo "${{ secrets.UAT_OVPN_USERNAME }}  ${{ secrets.UAT_OVPN_PASSWORD }}"
          echo "$OPENVPN_CONFIG" | sudo tee /etc/openvpn/client.conf > /dev/null
          echo "${{ secrets.UAT_OVPN_USERNAME }}" | sudo tee -a /etc/openvpn/client.conf > /dev/null
          echo "${{ secrets.UAT_OVPN_PASSWORD }}" | sudo tee -a /etc/openvpn/client.conf > /dev/null
          cat /etc/openvpn/client.conf
          
      - name: Start OpenVPN Connection
        run: sudo openvpn --config /etc/openvpn/client.conf --daemon

      - name: Sleep to Allow VPN Connection
        run: sleep 60
      
      - name: Deploy
        env:
          USER_NAME: ${{secrets.BAHMNI_LITE_AWS_UAT_MALAWI_SSH_USER_NAME}}
          HOSTNAME: ${{secrets.BAHMNI_LITE_AWS_UAT_MALAWI_SSH_HOST}}
        run: |
          ssh -i ~/private_key.pem -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
          ls -al
          '