name: Deploy to prod

on:
  push:
    branches:
      - githubActions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_LITE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.BAHMNI_LITE_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.BAHMNI_LITE_AWS_REGION }}
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.BAHMNI_LITE_AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - name: ssh auth
        env:
          EC2_IP: ${{secrets.EC2_MALAWI_IP}}
        run: |
          mkdir ~/.ssh
          echo "${EC2_IP} ecdsa-sha2-nistp256 AAAAE2V...=" >> ~/.ssh/known_hosts

      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.BAHMNI_LITE_AWS_SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.BAHMNI_LITE_AWS_SSH_HOST}}
          USER_NAME: ${{secrets.BAHMNI_LITE_AWS_SSH_USER_NAME}}
          EC2_IP: ${{secrets.EC2_MALAWI_IP}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no -o ProxyJump=${USER_NAME}@${HOSTNAME} ubuntu@${EC2_IP} '
          ls -al
          '

      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.BAHMNI_LITE_AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        if: always()

