name: Deploy to qa
on:
  push:
    branches:
      - githubActions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add pem file
        run: |
          echo "${{secrets.BAHMNI_LITE_AWS_UAT_SSH_PRIVATE_KEY}}" > ~/private_key.pem && chmod 400 ~/private_key.pem

      - name: Set Up and Start OpenVPN
        env:
          OPENVPN_CONFIG: ${{ secrets.UAT_OVPN_FILE }}
          OPENVPN_USERNAME: ${{ secrets.UAT_OVPN_USERNAME }}
          OPENVPN_PASSWORD: ${{ secrets.UAT_OVPN_PASSWORD }}
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
          echo "$OPENVPN_CONFIG" > vpn-config.ovpn
          echo "$OPENVPN_USERNAME" > vpn-credentials.txt
          echo "$OPENVPN_PASSWORD" >> vpn-credentials.txt
          sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon
          sleep 15

      - name: Deploy
        env:
          USER_NAME: ${{secrets.BAHMNI_LITE_AWS_UAT_MALAWI_SSH_USER_NAME}}
          HOSTNAME: ${{secrets.BAHMNI_LITE_AWS_UAT_MALAWI_SSH_HOST}}
        run: |
          ssh -i ~/private_key.pem -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
          ls -al
          '

      - name: Kill VPN connection
        if: always()
        run: |
          sudo killall openvpn